### ISSUE TITLE
Feature: add Opus support

### ISSUE THREAD

**Issue by thomas-mc-work** [nanocortex/metube-firefox-addon#5]
[Support for the Opus file format has been added recently to metube](https://github.com/alexta69/metube/commit/eca44aa950f82d518303e11c112267be2437abd0). It would be nice to have this option in the add on. Thanks a lot!

**Comment by nanocortex** [comment]
Thanks for suggestion! I've added all missing formats in version 1.3.4. It's gonna be in store after review.

**Comment by thomas-mc-work** [comment]
Thank you very much, that was very fast!
