### ISSUE TITLE
Feature Request: Support for basic auth

### ISSUE THREAD

**Issue by Emporea** [nanocortex/metube-firefox-addon#6]
To restrict access to metube instances, you could use basic authentication.

It would be useful to be able to set the username and password in the extension settings so that it can connect to instances that use basic authentication.

**Comment by nanocortex** [comment]
Correct me if I'm wrong, can't you just specify username and password in an instance url?

If not, I'd have to set up basic auth at my instance to reproduce this problem, so I need some time.
