### ISSUE TITLE
Add Auto Start as an option

### ISSUE THREAD

**Issue by BrightCandle** [nanocortex/metube-firefox-addon#7]
The latest version of Metube as of 13/12/2023 (was added a few days ago) has added an Auto start parameter which defaults to no and changes server side do not override what is sent to the Metube server by the extension. We need this parameter in the extension to make it possible to set it to automatically start the download rather than queueing it up.

Problem present in Version 1.3.4

**Comment by nanocortex** [comment]
Completed in https://github.com/nanocortex/metube-firefox-addon/pull/9
